<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8QG8CLM" failures="2" tests="3" name="Test" time="29.088" errors="0" timestamp="2022-03-27T13:58:57 IST">
  <testcase classname="TestClasses.AddNewAddress" name="verifyUserCanLogin" time="5.355"/>
  <testcase classname="TestClasses.AddNewAddress" name="verifyUserCanAddNewAddress" time="8.233">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at TestClasses.AddNewAddress.verifyUserCanAddNewAddress(AddNewAddress.java:103)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanAddNewAddress -->
  <testcase classname="TestClasses.AddNewAddress" name="verifyUserCanAddNewAddress" time="5.442">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at TestClasses.AddNewAddress.verifyUserCanAddNewAddress(AddNewAddress.java:103)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanAddNewAddress -->
</testsuite> <!-- Test -->
